<?php
namespace App\Enums;

enum CategorieAction: string
{
    case FONCTIONNEMENT = 'FONCTIONNEMENT';
    case DIFFUSION_DOC = 'DIFFUSION_DOC';
    case RECOMMANDATION_QS = 'RECOMMANDATION_QS';
    case PRISE_EN_COMPTE_DOC = 'PRISE_EN_COMPTE_DOC';
    case AUDIT = 'AUDIT';
    case ETUDE_SECURITE = 'ETUDE_SECURITE';
    case INSTRUCTION_FNE = 'INSTRUCTION_FNE';
    case RELECTURE_DOC = 'RELECTURE_DOC';
    case VALIDATION_AVENANT = 'VALIDATION_AVENANT';
    case SUIVI_MRR = 'SUIVI_MRR';
    case TRAITEMENT_RISQUE_CYBER = 'TRAITEMENT_RISQUE_CYBER';
    case REMEDIATION_INCIDENT_CYBER = 'REMEDIATION_INCIDENT_CYBER';
    case FEEDBACK_UTILISATEUR = 'FEEDBACK_UTILISATEUR';
    case TRAITEMENT_FEEDBACK = 'TRAITEMENT_FEEDBACK';
}