<?php
namespace App\Enums;

enum TypeEvenementHistoriqueAction: string
{
    case CREATION = 'CREATION';
    case CHANGEMENT_STATUT = 'CHANGEMENT_STATUT';
    case CHANGEMENT_AVANCEMENT = 'CHANGEMENT_AVANCEMENT';
    case COMMENTAIRE = 'COMMENTAIRE';
    case DEMANDE_REAJUSTEMENT = 'DEMANDE_REAJUSTEMENT';
    case APPROBATION_REAJUSTEMENT = 'APPROBATION_REAJUSTEMENT';
    case REFUS_REAJUSTEMENT = 'REFUS_REAJUSTEMENT';
    case CHANGEMENT_RESPONSABLE = 'CHANGEMENT_RESPONSABLE';
}